### ISSUE TITLE
Unable to find package Microsoft.DotNet.ILCompiler

### ISSUE THREAD

**Issue by gleblebedev** [teobugslayer/AvaloniaCoreRTDemo#12]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Microsoft.DotNet.ILCompiler. No packages exist with this id in source(s): LocalProject,  nuget.org
AvaloniaCoreRTDemo	C:\github\AvaloniaCoreRTDemo\src\AvaloniaCoreRTDemo.csproj	1	

It seems it isn't needed in the project?

**Comment by josephmoresena** [comment]
Does it happen when running the build script?

**Comment by teobugslayer** [comment]
The latest commit should have resolved the issue.

**Comment by josephmoresena** [comment]
Thanks!
