### ISSUE TITLE
Input box does not support Chinese

### ISSUE THREAD

**Issue by myFirstway** [teobugslayer/AvaloniaCoreRTDemo#18]
Input box does not support Chinese

**Comment by josephmoresena** [comment]
> Input box does not support Chinese

Is any output at console log? Platform?

**Comment by myFirstway** [comment]
Platform: 
版本	Windows 10 专业版
版本号	20H2
操作系统内部版本	19042.1526
体验	Windows Feature Experience Pack 120.2212.4170.0
![1646142614(1)](https://user-images.githubusercontent.com/7514693/156181125-23a4fb01-fb9a-4e16-abf9-88949f648e7f.png)


I cannot find the console log。。。。

**Comment by josephmoresena** [comment]
> I cannot find the console log。。。。

https://github.com/teobugslayer/AvaloniaCoreRTDemo/blob/440e8db6b09b0cde6db3de662f45e625b2a57c67/src/AvaloniaCoreRTDemo.csproj#L4-L5

Support of chinese/japanese characters may be related to:
* https://www.cnblogs.com/jasongrass/p/13758003.html
* https://github.com/Coding-Enthusiast/FinderOuter/issues/4
