### ISSUE TITLE
cannot run file .exe file in src\bin\Release\net5.0\win-x64\publish\

### ISSUE THREAD

**Issue by phuchoang78585** [teobugslayer/AvaloniaCoreRTDemo#23]
I downloaded the project to my computer and used the cmd command inside the folder picture 1:
![ảnh](https://user-images.githubusercontent.com/103045847/177433884-d38e0fe8-6574-488b-bbb6-727946848f11.png)
i download the project to my computer and use cmd command inside the folder and build with the command picture 2:
![ảnh](https://user-images.githubusercontent.com/103045847/177433910-821f43fa-d7e5-423c-bca8-4ffcb42d9d68.png)
but when the build is finished running the .exe file, it doesn't show anything, hope you can help me, thank you.

**Comment by phuchoang78585** [comment]
sorry, i am not very good at wpf or avalonia, i get the error like this
![ảnh](https://user-images.githubusercontent.com/103045847/177451751-f7dbf801-40b3-4c59-8daf-f5c1c44a04fd.png)
but i don't know how to fix it, hope you can help me, thank you

**Comment by teobugslayer** [comment]
Not sure what could be the problem. I've updated the project to the latest Avalonia UI nuget package and the readme file.

Please pull the new version of the project and give it a try.
