### ISSUE TITLE
ILC: Method will always throw because: Marshaling directives are invalid

### ISSUE THREAD

**Issue by ALIENQuake** [teobugslayer/AvaloniaCoreRTDemo#24]
Im getting this error:
```
ILC: Method '[S.P.CompilerGenerated]Internal.CompilerGenerated.<Module>.ReverseDelegateStub__GdipSetAdjustableArrowCapHeight_delegate(native int,float32)' will always throw because: Marshaling directives are invalid
  ILC: Method '[S.P.CompilerGenerated]Internal.CompilerGenerated.<Module>.ReverseOpenStaticDelegateStub__GdipSetAdjustableArrowCapHeight_delegate(native int,float32)' will always throw because: Marshaling directives are invalid
```
any clue?

**Comment by josephmoresena** [comment]
Platform?

**Comment by ALIENQuake** [comment]
Sorry, Windows 10/11.

EDIT: I can no longer reproduce it using NET 7.0.100-rc.2.22477.23

**Comment by josephmoresena** [comment]
The build of the [latest released artifact on Windows](https://github.com/teobugslayer/AvaloniaCoreRTDemo/actions/runs/2698600022/jobs/4212805816
) has several warnings about it, but it builds successfully.
The most important thing is that it works as it should. Warnings will be reduced as CoreCLR and Avalonia UI become more NativeAOT friendly. Even NativeAOT itself is getting better.
Are you able to get it working on Windows? Are you on x64 or arm64 architecture?

**Comment by ALIENQuake** [comment]
I'm using x64 architecture. Yes, it works for me now.
