### ISSUE TITLE
can not run in windows 7 x64

### ISSUE THREAD

**Issue by KevinL2015** [teobugslayer/AvaloniaCoreRTDemo#28]
missing "api-ms-win-core-heap-l2-1-0.dll"
![image](https://user-images.githubusercontent.com/13088124/208104679-9ff2d255-9aec-4426-82b9-1f0d3c832b4f.png)

**Comment by teobugslayer** [comment]
This is expected, because we bumped the project to requite .NET 7, which does not work on Windows 7.

You can download the latest sources which support .NET 6 and Windows 7 from the [Releases page](https://github.com/teobugslayer/AvaloniaCoreRTDemo/releases/tag/v0.10).
