### ISSUE TITLE
SkiaSharp is not included in executable.

### ISSUE THREAD

**Issue by FrankenApps** [teobugslayer/AvaloniaCoreRTDemo#3]
I am not sure, wether this is intentional, but SkiaSharp is still present as a DLL. I thought the prupose of CoreRT was to bundle all files in a native executable?

Would it be possible to include SkiaSharp in the executable, but is it ommited for some reason, or is it not possible to include that DLL?

Thanks in advance.

**Comment by teobugslayer** [comment]
Hi @FrankenApps,

CoreRT concerns itself only with managed code. On a very high level, CoreRT takes all managed assemblies - both yours and coming from the .NET core libraries such as mscorlib, then runs JIT and dumps the result in an .exe file, combined with small runtime pieces, like the garbage collector.

However, CoreRT does not deal with unmanaged dependencies. So, if you have unmanaged dependencies, such as Skia, SQLite, SDL2, or any other unmanaged dependency, you still need to distribute them among the .exe file produced by CoreRT.

If you absolutely need a single-file distribution, you can consider solutions such as [Warp](https://github.com/dgiagio/warp) which creates an self-extracting executable.

**Comment by FrankenApps** [comment]
I see. Thank you for the great explanation.
