### ISSUE TITLE
error CS0102: The type 'MainWindow' already contains a definition for 'MainControl'.

### ISSUE THREAD

**Issue by Disidente** [teobugslayer/AvaloniaCoreRTDemo#31]
error CS0102: The type 'MainWindow' already contains a definition for 'MainControl'.

**Comment by josephmoresena** [comment]
Avalonia UI 11 now generates code for any named element in the xaml, we're fixing this in #32.

It is very important to note that exists an InitializeComponent(bool, bool) -or InitializeComponent(bool) on Release or UserControl- method is now in the code generated from xaml.
